### ISSUE TITLE
[1.12.2] Crash upon digging BiomesoPlenty Block

### ISSUE THREAD

**Issue by Secretname2009** [Blaez-Dev/RWBYM-2.0#29] opened 2020-07-24 18:52 UTC
Title says everything, whenever i try to dig a Silty Grass Block from BOP then it ends up crashing. This is run as a LAN/Server for 2 other people and if one of the others try to do the same then it crashes the server.
As BiomesoPlenty support has ended for 1.12.2, i need to report it to you instead to see if you can do anything with this.
RWBY Mod is reported as one of the suspected mods.
[crash-2020-07-24_20.47.02-server.txt](https://github.com/Blaez-Dev/RWBYM/files/4973775/crash-2020-07-24_20.47.02-server.txt)

**Comment by Blaez-Dev** [comment] 2020-07-24 19:02
Caused by: java.lang.NullPointerException
    at biomesoplenty.common.block.BlockBOPGrass.getMaterial(BlockBOPGrass.java:141) the only thing we're doing is checking for the material. the bop block seems to return null as its marked as a vegetation block or something to that effect. tldr not much I can do since its a bop bug that's interfering with our method.

**Closed as completed by Blaez-Dev** 2020-07-24 19:02 UTC

**Comment by Secretname2009** [comment] 2020-07-24 19:04
Alright, well i asked atleast. Thanks for your attention.

**Comment by Blaez-Dev** [comment] 2020-07-24 19:08
any time, the root cause is we've got a item that doubles any vegetation/plant drops. their block method returns a npe when it shouldn't so its ultimately a issue with their code as we're doing things using vanilla methods.
