### ISSUE TITLE
Memory Leak/Mod Conflict

### ISSUE THREAD

**Issue by draveziovas** [Blaez-Dev/RWBYM-2.0#33] opened 2021-04-01 08:32 UTC
RWBYM conflicts with the Mod Sync (https://www.curseforge.com/minecraft/mc-mods/sync), in that RWBYM constantly outputs "[03:28:33] [Client thread/INFO] [rwbym]: No Current Semblance" every tick into the "latest.log" file and outputs 
"[15:09:44] [Client thread/DEBUG] [rwbym]: Getting Active Semblance for Player: (me)
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Ruby
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Weiss
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Yang
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Blake
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Ren
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Ragora
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Jaune
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Nora
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Qrow
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Lysette
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Clover
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: Harriet
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: pyrrha
[15:09:44] [Client thread/DEBUG] [rwbym]: Found Semblance: valour
[15:09:44] [Client thread/DEBUG] [rwbym]: Adding Semblance: valour"
into the "debug.log" file, likewise every tick.

This very rapidly takes up both filespace with the logs and eats up my RAM.

**Comment by Blaez-Dev** [comment] 2021-04-01 17:23
@draveziovas I'm sorry but could you do me a favour and check your minecraft forge version. this mod does not support past Forge 2847 due to Zero support from forge for 1.12.2 and changes that break alot of older mods. this issue could also be related to how the sync mod handles the death event. if it's canceling the event or other shenanigans there is not much we can do to resolve it. if you can send me the full log I can look into this further however without it I will have to refer you to above and mark sync as incompatible.

**Comment by Blaez-Dev** [comment] 2021-04-01 17:26
https://adfoc.us/serve/sitelinks/?id=271228&url=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2836/forge-1.12.2-14.23.5.2836-universal.jar to ensure it's not the forge version you can try this version here and get back to me.

**Comment by draveziovas** [comment] 2021-04-03 04:49
I've uploaded the log to https://paste.ee/p/lNdPh

The log is for a fresh minecraft save using the forge version you listed and only rwbym, Sync, and JEI.

**Comment by Blaez-Dev** [comment] 2021-04-03 05:30
it seems like there's some error with the UUID; which might be causing some issue setting the semblance initially on world load. I'm not 100% sure of the cause however; you might be able to fix it by using /semblance player semblanceName level however I'm not sure what sync does 100% but anything that interferes with the death event ((canceling or otherwise)) is incompatible due to use using this event to re-set the players semblance when that doesn't happen you can get the errors above so sync will have to be marked as incompatible.

**Closed as completed** 2021-04-26 06:24 UTC
